name: reset_life
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.5
  custom_lint: ^0.7.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^11.2.0
  flutter_stripe_web: ^6.2.0
  go_router: ^14.4.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  pay: ^2.0.0
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  sembast: ^3.7.5+2
  sembast_web: ^2.4.0+4
  syncfusion_flutter_charts: ^27.2.2
  table_calendar: ^3.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  generate: true
