// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9dBnoKOXn6NEV9_nT0nXsZJRgIgndVhM',
    appId: '1:189361738963:web:4d561fad3408f8e7757026',
    messagingSenderId: '189361738963',
    projectId: 'reset-life-prod',
    authDomain: 'reset-life-prod.firebaseapp.com',
    storageBucket: 'reset-life-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtia7UvJ-Y1tK7Bg4SRDpxDx67W_8G1J4',
    appId: '1:189361738963:android:5293aefaa0dd445b757026',
    messagingSenderId: '189361738963',
    projectId: 'reset-life-prod',
    storageBucket: 'reset-life-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnloXdfElgIN8z6m_sG2OMFDjQr84G1qI',
    appId: '1:189361738963:ios:e40235fadec2e68f757026',
    messagingSenderId: '189361738963',
    projectId: 'reset-life-prod',
    storageBucket: 'reset-life-prod.firebasestorage.app',
    iosBundleId: 'com.example.resetLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnloXdfElgIN8z6m_sG2OMFDjQr84G1qI',
    appId: '1:189361738963:ios:e40235fadec2e68f757026',
    messagingSenderId: '189361738963',
    projectId: 'reset-life-prod',
    storageBucket: 'reset-life-prod.firebasestorage.app',
    iosBundleId: 'com.example.resetLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9dBnoKOXn6NEV9_nT0nXsZJRgIgndVhM',
    appId: '1:189361738963:web:669d00122ac7f796757026',
    messagingSenderId: '189361738963',
    projectId: 'reset-life-prod',
    authDomain: 'reset-life-prod.firebaseapp.com',
    storageBucket: 'reset-life-prod.firebasestorage.app',
  );
}
